[parameters]
kappaT = 1.0
kappaN = 0.0
kappaB = 0.0
charge = 1.0
tratio = 1.0

# Collisional operator factors 
# If not specified, will be computed from tratio and charge
coeffa = -1.0
coeffb = -1.0
coeffc = -1.0

[parameters.frozen]
cutoff_ikx = 1
cutoff_iky = 1
cutoff_ikz = 1

amplitude = -1.0
